
name: Generate Documentation PDF

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-pdf:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build PDF source
        run: node scripts/build-pdf.js

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-xetex -y

      - name: Show generated markdown
        run: |
          head -100 pdf/output/datasuite-book.md
      - name: Search for LaTeX
        run: |
          grep -n "N_" pdf/output/datasuite-book.md || true
          grep -n "\\\\times" pdf/output/datasuite-book.md || true  
      - name: Generate PDF
        run: |
          mkdir -p pdf/output

          pandoc \
          pdf/output/datasuite-book.md \
          --pdf-engine=xelatex \
          -o pdf/output/datasuite-en.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: datasuite-documentation
          path: pdf/output/datasuite-en.pdf
